### ISSUE TITLE
Activity?

### ISSUE THREAD

**Issue by kieraneglin** [migeorge/erb-helper#10]
Hello,

Are you still taking PR's on this project?  If so, I'd like to submit one, but I don't want to write it out if this project is no longer maintained.

Thank you!

**Comment by migeorge** [comment]
I'd be happy to accept a PR if it aligns with the project. What are you thinking of adding?

**Comment by kieraneglin** [comment]
Thanks for the quick reply!

I figure that the context menu should only appear within the Atom workspace.

Right now, you can have a file open, right click on a different file in the tree view, and still see `ERB * Tag`.  A tag is then inserted in the file that's currently open.

In my mind, a better solution would be to limit these context menus to Atom's editor only.  This can be done by changing this:

```coffeescript
# /menus/erb-helper.cson

'context-menu':
  'atom-workspace': [
    {label: 'ERB Output Tag',  command: 'erb-helper:output'}
    {label: 'ERB Eval Tag',    command: 'erb-helper:eval' }
    {label: 'ERB Comment Tag', command: 'erb-helper:comment'}
]
```

to this

```coffeescript
'context-menu':
  'atom-text-editor': [
    {label: 'ERB Output Tag',  command: 'erb-helper:output'}
    {label: 'ERB Eval Tag',    command: 'erb-helper:eval' }
    {label: 'ERB Comment Tag', command: 'erb-helper:comment'}
]
```

I haven't tested this yet, but I think it'd be that simple.  

Thoughts?

**Comment by migeorge** [comment]
Great catch! I agree completely, if you want to submit a PR I'd appreciate it. Otherwise I'll add it to my backlog. Thanks!
