### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [migeorge/erb-helper#6]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.2.1`) of this package:
1. The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.
2. Use `activationCommands` instead of `activationEvents` in your package.json Commands should be grouped by selector as follows: `json "activationCommands": { "atom-workspace": ["foo:bar", "foo:baz"], "atom-text-editor": ["foo:quux"] }`
3. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
4. Use ::getActivePaneItem() instead of the ::activePaneItem property
5. Use TextEditor::getLastSelection() instead
6. Use TextEditor::moveLeft() instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by migeorge** [comment]
I will be working on a fix shortly, I actually use vim as my primary editor now so I don't use atom much anymore. I'll continue to support this plugin so long as the demand is there.

**Comment by migeorge** [comment]
erb-helper now conforms with the 1.0 API and no longer relies on the deprecated functions mentioned.

**Comment by benogle** [comment]
:heart:
