### ISSUE TITLE
Keybindings not working

### ISSUE THREAD

**Issue by peyloride** [migeorge/erb-helper#7]
Hello, this is my first issue report; so if i doing this wrong please be gentle.

I'm learning Ruby on Rails and i love Atom. I want to use your package but i cant get it to working.

When i right-click and select ERB-Output tag for example, it works.

But when i do Ctrl - . it makes the line in comment like # blabla

What must i do further or what am i missing?

**Comment by migeorge** [comment]
I can't reproduce this issue.

Try the Atom keybinding-resolver plugin to see if you have clashing keybindings:
https://atom.io/packages/keybinding-resolver

Thanks!
